config/routes.rb
StreamingTest::Application.routes.draw do
  root to: 'home#index'
  post '/login', to: 'sessions#login', as: "login"
  post '/logout', to: 'sessions#logout', as: "logout"
  post '/video_form', to: 'home#changevid', as: "set_video_source"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
	attr_accessor :password
		
	def self.authenticate(email,password)
		user = Admin.find_by_email(email)
		if user && user.match_password(password)
			return user
		else
			return false
		end
	end

	def match_password(login_password)
		return encrypted_password == BCrypt::Engine.hash_secret(login_password,salt)
	end
end

app/models/video.rb
class Video < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  	@admin = Admin.new
  	@video = Video.find(1)
  end

  def changevid
  	if session[:user]
  		Video.find(1).update(source: params[:src])
  	else
  		return false
  	end
  	redirect_to :root
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def login
		authorized_user = Admin.authenticate(params[:email], params[:password])
		if authorized_user
			session[:user] = authorized_user
		else
			flash[:notice] = 'login failed'
		end
		redirect_to :root
	end

	def logout
		session[:user] = nil
		redirect_to :root
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.erb
<% if session[:user] %>
	<p> Welcome, <%=session[:user].email %>!</p>
	<%= form_tag logout_path do %>
		<%= submit_tag("Log Out") %>
	<% end %>
<% end %>
<p><%= flash[:notice] %></p>
<% if session[:user] %>
	<%= form_tag set_video_source_path do %>
		<%= text_field_tag(:src, @video.source) %>
		<%= submit_tag("Submit") %>
	<% end %>
<% end %>
<button type="button" id="logintoggle">Open Admin Login Form</button>
<video controls>
	<source src="<%=@video.source%>" type="video/webm">
</video>
<%= form_tag login_path, id: "loginform" do %>
	<p><%= label_tag :email %> <%= text_field_tag(:email) %></p>
	<p><%= label_tag :password %> <%= password_field_tag(:password) %></p>
	<%= submit_tag("Log In") %>
<% end %>

<script type="text/javascript">
	$('#loginform').hide();
	$('#logintoggle').click(function() {
		$('#loginform').toggle();
	});



	<% if session[:user] %>
	$('#logintoggle').hide()
	$('#loginform').hide()
	<% end %>

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StreamingTest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>